main: me.nahuld.antihostile.Main
version: v0.0.4

name: AntiHostile
description: Don't let ugly entities target you anymore!

author: NahuLD

commands:
  antihostile:
    description: Antihostile plugin command.
    permission: antihostile.toggle

permissions:
  antihostile.toggle:
    default: op
    description: Antihostile only permission.